name: Deploy `Kalakairali Member Management System` app to Firebase

on:
  push:
    branches:
      - dev   # Deploys to Dev Firebase (kk-contact-app)
      - main  # Deploys to Prod Firebase

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Checkout Repo
        uses: actions/checkout@v4

      # 2. Setup Node
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Install deps (root + functions)
      - name: Install dependencies
        run: |
          npm install
          cd functions
          npm install
          cd ..

      # 4. Inject .env from GitHub Secrets
      # Create .env file for Dev
      - name: Create .env for Dev
        if: github.ref_name == 'dev'
        run: |
          echo "${{ secrets.ENV_FILE_DEV }}" > .env

      # Create .env file for Prod
      - name: Create .env for Prod
        if: github.ref_name == 'main'
        run: |
          echo "${{ secrets.ENV_FILE_PROD }}" > .env

      # 5. Build React App with correct mode
      # Build React App Dev
      - name: Build React App Dev
        if: github.ref_name == 'dev'
        run: npm run build -- --mode development

      # Build React App Prod
      - name: Build React App Prod
        if: github.ref_name == 'main'
        run: npm run build -- --mode production

      # 6. Deploy to Firebase
      # Deploy to Firebase Dev
      - name: Deploy to Firebase Dev
        if: github.ref == 'refs/heads/dev' # or if: github.ref_name == 'dev'
        uses: w9jds/firebase-action@v13
        with:
          args: deploy --only hosting,functions --project ${{ secrets.PROJECT_ID_DEV }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_DEV }}

      # Deploy to Firebase Prod
      - name: Deploy to Firebase Prod
        if: github.ref == 'refs/heads/main' # or if: github.ref_name == 'main'
        uses: w9jds/firebase-action@v13
        with:
          args: deploy --only hosting,functions --project ${{ secrets.PROJECT_ID_PROD }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_PROD }}
